#!/bin/sh

usb_enabled() {
	return 0
}

usb_run() {
	echo "not implemented"
	#dd if=/dev/zero of=/usb.vfat bs=512 count=2048
	#mkfs.vfat -n "USB Storage" /usb.vfat
	#modprobe g_mass_storage file=/usb.vfat
}
